### ISSUE TITLE
Error while getting repo2.maven to /root/.ant/lib/ivy.jar

### ISSUE THREAD

**Issue by daywin94** [rdpstaff/classifier#24]
Hello,

I tried to solve this issue for a couple of hours but nothing worked for me.
I tired to build the tools with sudo make but everytime I am running into the same issue (see below)

ant -f Clustering/build.xml jar
Buildfile: /home/davin/Documents/RDPTools/Clustering/build.xml

download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Error getting http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar to /root/.ant/lib/ivy.jar

BUILD FAILED
/home/davin/Documents/RDPTools/Clustering/build.xml:87: java.net.UnknownHostException: repo2.maven.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:766)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:676)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:666)

Total time: 0 seconds
Makefile:15: recipe for target 'Clustering/dist/Clustering.jar' failed
make: *** [Clustering/dist/Clustering.jar] Error 1

I tried to clone the repository to my home and ran it again. I also installed JDK version 8 and I made sure my ant version is up to date. Nothing seems to work from the other solutions I found so I opened this issue here.

Thanks in advance for any help!

**Comment by osageorange** [comment]
I think this is because the URL is no longer valid for. I was able to solve this by changing the first part of the link on line 26 of the build.xml file to 'https://repo1.maven.org/maven2/org/apache/ivy/ivy/' 

I hope that works for you!
